# Generated by Django 5.2.8 on 2025-11-30 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(help_text='Name of the category', max_length=100)),
                ('description', models.TextField(help_text='Category description')),
                ('image', models.ImageField(help_text='Recommended size: 400x300 pixels', upload_to='homepage/categories/')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Category Banner',
                'verbose_name_plural': 'Category Banners',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='FeaturedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='homepage/featured/')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Featured Product',
                'verbose_name_plural': 'Featured Products',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='HomepageBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title for the banner', max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='Subtitle or description', max_length=300)),
                ('image', models.ImageField(help_text='Recommended size: 1200x600 pixels', upload_to='homepage/banners/')),
                ('is_active', models.BooleanField(default=True, help_text='Show this banner on homepage')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which banners are displayed')),
                ('button_text', models.CharField(blank=True, default='Shop Now', max_length=50)),
                ('button_link', models.CharField(blank=True, default='/products/', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Homepage Banner',
                'verbose_name_plural': 'Homepage Banners',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
